### ISSUE TITLE
can we get results back as json?

### ISSUE THREAD

**Issue by ralyodio** [TUVIMEN/torge#3]
I'd like to use this as an api on my streaming app, but I need results in json.

**Comment by ralyodio** [comment]
it looks like reliq supports json output.

**Comment by TUVIMEN** [comment]
If you think about it torge already returns something close to csv list.

I've just [added](https://github.com/TUVIMEN/torge/commit/15b3c792560c42778483b3f8f2c588ba35d36bbc) `--csv` option so that line number will not be printed and links will be added at the end of record.

Most sites don't store magnet links in search pages and they have to be downloaded from selected page, so by default `link` field points to whatever link is found.

If you want magnet links use `--csv` and `--link-conv` options, but note that this will take a couple seconds to go through all of them.

You can also change default delimiter `\t` with `-D` option.

**Comment by ralyodio** [comment]
i don't need csv i need json. should be easy to add a --json flag no?

**Comment by TUVIMEN** [comment]
`--json` option has been [added](https://github.com/TUVIMEN/torge/commit/3b4cb704b42ab37ce8c324d64c2f85911ee286e5).

**Comment by TUVIMEN** [comment]
This also adds `jq` to the list of dependencies.

**Comment by ralyodio** [comment]
thanks
