### ISSUE TITLE
any other features you are adding?

### ISSUE THREAD

**Issue by ralyodio** [TUVIMEN/torge#8]
Works great for my torrent search api on zymo.tv

i'm curious if you plan on adding any other providers and/or features.

**Comment by ralyodio** [comment]
can you add a `--proxy` flag to torget with format of `http://user:pass@ip`

**Comment by TUVIMEN** [comment]
I'm open for suggestions.

For features i thought about full fzf integration but they don't support table formatting so it's on hold for now.

As for providers, i don't know many other.   I've tried to implement `YTS` support, but it's more of an app rather than searching platform and interface with it would have to be different than for other sources.

**Comment by ralyodio** [comment]
What's fzf?

**Comment by TUVIMEN** [comment]
[A command-line fuzzy finder](https://github.com/junegunn/fzf)

**Comment by ralyodio** [comment]
Is it you can figure this out (I've tried for years) but crawling the DHT would be epic
